### ISSUE TITLE
Button inside HyperlinkButton not working in fayde

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#189] opened 2015-10-13 06:08 UTC
Button inside HyperlinkButton not working in fayde

```
<HyperlinkButton TargetName="_blank" NavigateUri="{Binding Path=FileUri}">
   <Button Height="32" Width="32" HorizontalAlignment="Right"
                                                  VerticalAlignment="Top"                                                  
                                                  Tag="Test"
                                                  Margin="-3"
                                                  Command="{Binding Path=Parent.DeleteFileCommand}"
                                                  CommandParameter="{Binding }" />
  </HyperlinkButton>
```

**Comment by BSick7** [comment] 2015-10-13 12:55
Please leave version info and description of what is not working.

**Comment by BSick7** [comment] 2016-02-25 14:06
Duplicate of #239.
Please refrain from creating multiple issues in github with the same bug.

**Closed by BSick7** 2016-02-25 14:06 UTC
