### ISSUE TITLE
HyperlinkButton TargetName _Blank not working in IE11

### ISSUE THREAD

**Issue by deepaksm1** [wsick/Fayde#249] opened 2016-02-25 11:16 UTC
HyperlinkButton TargetName = _Blank not working in IE11.
Page should open in new window if target is _Blank. 
```
<HyperlinkButton Content="Download" Foreground="Teal" NavigateUri="http://www.google.com" TargetName="_Blank" />
```
I created new fayde application and just added above code in default.fap. But link is not opening in new window.

In fayde to open link in new window below code is used:
```
  function launchDummyLink(target, navigateUri) {
            dummyLink = dummyLink || document.createElement('a');
            dummyLink.href = navigateUri;
            dummyLink.target = target;
            dummyLink.click();
        }
```

You are actually only creating the element, without adding it to the DOM. And trying to fire click event which doesn't support in IE.

See below URL for reference:
http://stackoverflow.com/questions/24953662/click-event-not-firing-in-ie11
http://stackoverflow.com/questions/27860719/click-not-being-invoked-on-link-element

**Comment by deepaksm1** [comment] 2016-02-25 11:17
Please check in IE11

**Comment by BSick7** [comment] 2016-02-25 14:09
Duplicate of #206 
Please refrain from opening the same issue. Comment on existing issue.

**Closed by BSick7** 2016-02-25 14:09 UTC
